/********************************************************************************
** Form generated from reading UI file 'home_ui.ui'
**
** Created by: Qt User Interface Compiler version 5.6.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_HOME_UI_H
#define UI_HOME_UI_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_home_ui
{
public:
    QWidget *centralWidget;
    QPushButton *GUARD_BUTTON;
    QPushButton *PHONE_BUTTON;
    QPushButton *GATE_BUTTON;
    QPushButton *PARK_BUTTON;
    QPushButton *CCTV_BUTTON;
    QPushButton *SETTING;
    QLabel *TITLE_BUTTON;
    QLabel *GUARD_TITLE;
    QLabel *PHONE_TITLE;
    QLabel *GATE_TITLE;
    QLabel *SETTING_TITLE;
    QLabel *CCTV_TITLE;
    QLabel *PARK_TITLE;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *PARK_SCENE_TITLE;
    QPushButton *PARKscene;
    QPushButton *PARKscene_3;
    QPushButton *PARKscene_2;
    QPushButton *PARKscene_4;
    QLabel *PARK_INFO_SCENE_2;
    QPushButton *PARK1_camera;
    QLabel *PARK1_BACKGROUND;
    QLabel *PARK1_5;
    QLabel *PARK1_6;
    QLabel *PARK1_4;
    QLabel *PARK1_1;
    QLabel *PARK1_2;
    QLabel *PARK1_3;
    QPushButton *PARK1_go_PARK2;
    QPushButton *PARK1_go_HOME;
    QLabel *PARK1_camera_txt;
    QPushButton *PARK1_go_Park_select;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *home_ui)
    {
        if (home_ui->objectName().isEmpty())
            home_ui->setObjectName(QStringLiteral("home_ui"));
        home_ui->resize(892, 425);
        centralWidget = new QWidget(home_ui);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        GUARD_BUTTON = new QPushButton(centralWidget);
        GUARD_BUTTON->setObjectName(QStringLiteral("GUARD_BUTTON"));
        GUARD_BUTTON->setGeometry(QRect(90, 110, 121, 101));
        GUARD_BUTTON->setAutoDefault(false);
        PHONE_BUTTON = new QPushButton(centralWidget);
        PHONE_BUTTON->setObjectName(QStringLiteral("PHONE_BUTTON"));
        PHONE_BUTTON->setGeometry(QRect(390, 110, 121, 101));
        GATE_BUTTON = new QPushButton(centralWidget);
        GATE_BUTTON->setObjectName(QStringLiteral("GATE_BUTTON"));
        GATE_BUTTON->setGeometry(QRect(680, 110, 121, 101));
        PARK_BUTTON = new QPushButton(centralWidget);
        PARK_BUTTON->setObjectName(QStringLiteral("PARK_BUTTON"));
        PARK_BUTTON->setGeometry(QRect(90, 270, 121, 101));
        CCTV_BUTTON = new QPushButton(centralWidget);
        CCTV_BUTTON->setObjectName(QStringLiteral("CCTV_BUTTON"));
        CCTV_BUTTON->setGeometry(QRect(390, 270, 121, 101));
        SETTING = new QPushButton(centralWidget);
        SETTING->setObjectName(QStringLiteral("SETTING"));
        SETTING->setGeometry(QRect(679, 270, 121, 101));
        TITLE_BUTTON = new QLabel(centralWidget);
        TITLE_BUTTON->setObjectName(QStringLiteral("TITLE_BUTTON"));
        TITLE_BUTTON->setGeometry(QRect(0, -30, 891, 451));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(248, 248, 248, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(251, 251, 251, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(124, 124, 124, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(165, 165, 165, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        QBrush brush6(QColor(255, 255, 220, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        TITLE_BUTTON->setPalette(palette);
        QFont font;
        font.setPointSize(25);
        font.setBold(true);
        font.setWeight(75);
        TITLE_BUTTON->setFont(font);
        TITLE_BUTTON->setAutoFillBackground(true);
        TITLE_BUTTON->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        GUARD_TITLE = new QLabel(centralWidget);
        GUARD_TITLE->setObjectName(QStringLiteral("GUARD_TITLE"));
        GUARD_TITLE->setGeometry(QRect(70, 210, 161, 31));
        QFont font1;
        font1.setFamily(QString::fromUtf8("\355\234\264\353\250\274\353\247\244\354\247\201\354\262\264"));
        font1.setPointSize(13);
        font1.setBold(false);
        font1.setWeight(50);
        GUARD_TITLE->setFont(font1);
        GUARD_TITLE->setAlignment(Qt::AlignCenter);
        PHONE_TITLE = new QLabel(centralWidget);
        PHONE_TITLE->setObjectName(QStringLiteral("PHONE_TITLE"));
        PHONE_TITLE->setGeometry(QRect(370, 210, 161, 31));
        PHONE_TITLE->setFont(font1);
        PHONE_TITLE->setAlignment(Qt::AlignCenter);
        GATE_TITLE = new QLabel(centralWidget);
        GATE_TITLE->setObjectName(QStringLiteral("GATE_TITLE"));
        GATE_TITLE->setGeometry(QRect(660, 210, 161, 31));
        GATE_TITLE->setFont(font1);
        GATE_TITLE->setAlignment(Qt::AlignCenter);
        SETTING_TITLE = new QLabel(centralWidget);
        SETTING_TITLE->setObjectName(QStringLiteral("SETTING_TITLE"));
        SETTING_TITLE->setGeometry(QRect(660, 370, 161, 31));
        SETTING_TITLE->setFont(font1);
        SETTING_TITLE->setAlignment(Qt::AlignCenter);
        CCTV_TITLE = new QLabel(centralWidget);
        CCTV_TITLE->setObjectName(QStringLiteral("CCTV_TITLE"));
        CCTV_TITLE->setGeometry(QRect(370, 370, 161, 31));
        CCTV_TITLE->setFont(font1);
        CCTV_TITLE->setAlignment(Qt::AlignCenter);
        PARK_TITLE = new QLabel(centralWidget);
        PARK_TITLE->setObjectName(QStringLiteral("PARK_TITLE"));
        PARK_TITLE->setGeometry(QRect(70, 370, 161, 31));
        PARK_TITLE->setFont(font1);
        PARK_TITLE->setAlignment(Qt::AlignCenter);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(90, 110, 121, 101));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        label->setPalette(palette1);
        label->setAutoFillBackground(true);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(390, 270, 121, 101));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        label_2->setPalette(palette2);
        label_2->setAutoFillBackground(true);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(390, 110, 121, 101));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        label_3->setPalette(palette3);
        label_3->setAutoFillBackground(true);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(90, 270, 121, 101));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        label_4->setPalette(palette4);
        label_4->setAutoFillBackground(true);
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(680, 270, 121, 101));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        label_5->setPalette(palette5);
        label_5->setAutoFillBackground(true);
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(680, 110, 121, 101));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        label_6->setPalette(palette6);
        label_6->setAutoFillBackground(true);
        PARK_SCENE_TITLE = new QLabel(centralWidget);
        PARK_SCENE_TITLE->setObjectName(QStringLiteral("PARK_SCENE_TITLE"));
        PARK_SCENE_TITLE->setGeometry(QRect(0, -30, 891, 451));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        PARK_SCENE_TITLE->setPalette(palette7);
        PARK_SCENE_TITLE->setFont(font);
        PARK_SCENE_TITLE->setAutoFillBackground(true);
        PARK_SCENE_TITLE->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        PARKscene = new QPushButton(centralWidget);
        PARKscene->setObjectName(QStringLiteral("PARKscene"));
        PARKscene->setGeometry(QRect(50, 140, 151, 131));
        QFont font2;
        font2.setFamily(QString::fromUtf8("\355\234\264\353\250\274\353\247\244\354\247\201\354\262\264"));
        font2.setPointSize(25);
        PARKscene->setFont(font2);
        PARKscene_3 = new QPushButton(centralWidget);
        PARKscene_3->setObjectName(QStringLiteral("PARKscene_3"));
        PARKscene_3->setGeometry(QRect(490, 140, 151, 131));
        QFont font3;
        font3.setFamily(QString::fromUtf8("\355\234\264\353\250\274\353\247\244\354\247\201\354\262\264"));
        font3.setPointSize(27);
        PARKscene_3->setFont(font3);
        PARKscene_2 = new QPushButton(centralWidget);
        PARKscene_2->setObjectName(QStringLiteral("PARKscene_2"));
        PARKscene_2->setGeometry(QRect(270, 140, 151, 131));
        PARKscene_2->setFont(font2);
        PARKscene_4 = new QPushButton(centralWidget);
        PARKscene_4->setObjectName(QStringLiteral("PARKscene_4"));
        PARKscene_4->setGeometry(QRect(700, 140, 151, 131));
        QFont font4;
        font4.setFamily(QString::fromUtf8("\355\234\264\353\250\274\353\247\244\354\247\201\354\262\264"));
        font4.setPointSize(27);
        font4.setBold(true);
        font4.setWeight(75);
        PARKscene_4->setFont(font4);
        PARK_INFO_SCENE_2 = new QLabel(centralWidget);
        PARK_INFO_SCENE_2->setObjectName(QStringLiteral("PARK_INFO_SCENE_2"));
        PARK_INFO_SCENE_2->setGeometry(QRect(0, -30, 891, 451));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        PARK_INFO_SCENE_2->setPalette(palette8);
        PARK_INFO_SCENE_2->setFont(font);
        PARK_INFO_SCENE_2->setAutoFillBackground(true);
        PARK_INFO_SCENE_2->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        PARK1_camera = new QPushButton(centralWidget);
        PARK1_camera->setObjectName(QStringLiteral("PARK1_camera"));
        PARK1_camera->setGeometry(QRect(470, 140, 141, 121));
        PARK1_BACKGROUND = new QLabel(centralWidget);
        PARK1_BACKGROUND->setObjectName(QStringLiteral("PARK1_BACKGROUND"));
        PARK1_BACKGROUND->setGeometry(QRect(30, 100, 391, 301));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        PARK1_BACKGROUND->setPalette(palette9);
        PARK1_BACKGROUND->setAutoFillBackground(true);
        PARK1_5 = new QLabel(centralWidget);
        PARK1_5->setObjectName(QStringLiteral("PARK1_5"));
        PARK1_5->setGeometry(QRect(170, 270, 91, 121));
        PARK1_5->setAutoFillBackground(true);
        PARK1_6 = new QLabel(centralWidget);
        PARK1_6->setObjectName(QStringLiteral("PARK1_6"));
        PARK1_6->setGeometry(QRect(280, 270, 91, 121));
        PARK1_6->setAutoFillBackground(true);
        PARK1_4 = new QLabel(centralWidget);
        PARK1_4->setObjectName(QStringLiteral("PARK1_4"));
        PARK1_4->setGeometry(QRect(60, 270, 91, 121));
        PARK1_4->setAutoFillBackground(true);
        PARK1_1 = new QLabel(centralWidget);
        PARK1_1->setObjectName(QStringLiteral("PARK1_1"));
        PARK1_1->setGeometry(QRect(60, 110, 91, 121));
        PARK1_1->setAutoFillBackground(true);
        PARK1_2 = new QLabel(centralWidget);
        PARK1_2->setObjectName(QStringLiteral("PARK1_2"));
        PARK1_2->setGeometry(QRect(170, 110, 91, 121));
        PARK1_2->setAutoFillBackground(true);
        PARK1_3 = new QLabel(centralWidget);
        PARK1_3->setObjectName(QStringLiteral("PARK1_3"));
        PARK1_3->setGeometry(QRect(280, 110, 91, 121));
        PARK1_3->setAutoFillBackground(true);
        PARK1_go_PARK2 = new QPushButton(centralWidget);
        PARK1_go_PARK2->setObjectName(QStringLiteral("PARK1_go_PARK2"));
        PARK1_go_PARK2->setGeometry(QRect(690, 110, 181, 71));
        QFont font5;
        font5.setFamily(QString::fromUtf8("\355\234\264\353\250\274\353\247\244\354\247\201\354\262\264"));
        font5.setPointSize(16);
        font5.setBold(true);
        font5.setWeight(75);
        PARK1_go_PARK2->setFont(font5);
        PARK1_go_HOME = new QPushButton(centralWidget);
        PARK1_go_HOME->setObjectName(QStringLiteral("PARK1_go_HOME"));
        PARK1_go_HOME->setGeometry(QRect(690, 220, 181, 71));
        PARK1_go_HOME->setFont(font5);
        PARK1_camera_txt = new QLabel(centralWidget);
        PARK1_camera_txt->setObjectName(QStringLiteral("PARK1_camera_txt"));
        PARK1_camera_txt->setGeometry(QRect(470, 260, 141, 41));
        QFont font6;
        font6.setFamily(QString::fromUtf8("\355\234\264\353\250\274\353\247\244\354\247\201\354\262\264"));
        font6.setPointSize(20);
        font6.setBold(false);
        font6.setWeight(50);
        PARK1_camera_txt->setFont(font6);
        PARK1_camera_txt->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        PARK1_go_Park_select = new QPushButton(centralWidget);
        PARK1_go_Park_select->setObjectName(QStringLiteral("PARK1_go_Park_select"));
        PARK1_go_Park_select->setGeometry(QRect(690, 320, 181, 71));
        QFont font7;
        font7.setFamily(QString::fromUtf8("\355\234\264\353\250\274\353\247\244\354\247\201\354\262\264"));
        font7.setPointSize(18);
        PARK1_go_Park_select->setFont(font7);
        home_ui->setCentralWidget(centralWidget);
        label_4->raise();
        label_2->raise();
        label_5->raise();
        label_6->raise();
        label_3->raise();
        label->raise();
        TITLE_BUTTON->raise();
        GUARD_BUTTON->raise();
        PHONE_BUTTON->raise();
        GATE_BUTTON->raise();
        PARK_BUTTON->raise();
        CCTV_BUTTON->raise();
        SETTING->raise();
        GUARD_TITLE->raise();
        PHONE_TITLE->raise();
        GATE_TITLE->raise();
        SETTING_TITLE->raise();
        CCTV_TITLE->raise();
        PARK_TITLE->raise();
        PARK_SCENE_TITLE->raise();
        PARKscene->raise();
        PARKscene_3->raise();
        PARKscene_2->raise();
        PARKscene_4->raise();
        PARK_INFO_SCENE_2->raise();
        PARK1_camera->raise();
        PARK1_BACKGROUND->raise();
        PARK1_5->raise();
        PARK1_6->raise();
        PARK1_4->raise();
        PARK1_1->raise();
        PARK1_2->raise();
        PARK1_3->raise();
        PARK1_go_PARK2->raise();
        PARK1_go_HOME->raise();
        PARK1_camera_txt->raise();
        PARK1_go_Park_select->raise();
        statusBar = new QStatusBar(home_ui);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        home_ui->setStatusBar(statusBar);

        retranslateUi(home_ui);

        QMetaObject::connectSlotsByName(home_ui);
    } // setupUi

    void retranslateUi(QMainWindow *home_ui)
    {
        home_ui->setWindowTitle(QApplication::translate("home_ui", "home_ui", 0));
        GUARD_BUTTON->setText(QString());
        PHONE_BUTTON->setText(QString());
        GATE_BUTTON->setText(QString());
        PARK_BUTTON->setText(QString());
        CCTV_BUTTON->setText(QString());
        SETTING->setText(QString());
        TITLE_BUTTON->setText(QApplication::translate("home_ui", "\n"
"\354\212\244\353\247\210\355\212\270 \355\231\210 \354\235\270\355\204\260\355\217\260", 0));
        GUARD_TITLE->setText(QApplication::translate("home_ui", "\352\262\275\353\271\204\354\213\244", 0));
        PHONE_TITLE->setText(QApplication::translate("home_ui", "\354\204\270\353\214\200\355\206\265\355\231\224", 0));
        GATE_TITLE->setText(QApplication::translate("home_ui", "\355\230\204\352\264\200\353\263\264\352\270\260", 0));
        SETTING_TITLE->setText(QApplication::translate("home_ui", "\354\204\244\354\240\225", 0));
        CCTV_TITLE->setText(QApplication::translate("home_ui", "CCTV", 0));
        PARK_TITLE->setText(QApplication::translate("home_ui", "\354\243\274\354\260\250\355\230\204\355\231\251", 0));
        label->setText(QApplication::translate("home_ui", "TextLabel", 0));
        label_2->setText(QApplication::translate("home_ui", "TextLabel", 0));
        label_3->setText(QApplication::translate("home_ui", "TextLabel", 0));
        label_4->setText(QApplication::translate("home_ui", "TextLabel", 0));
        label_5->setText(QApplication::translate("home_ui", "TextLabel", 0));
        label_6->setText(QApplication::translate("home_ui", "TextLabel", 0));
        PARK_SCENE_TITLE->setText(QApplication::translate("home_ui", "\n"
"\354\243\274\354\260\250\355\230\204\355\231\251", 0));
        PARKscene->setText(QApplication::translate("home_ui", "PARK1", 0));
        PARKscene_3->setText(QApplication::translate("home_ui", "\353\202\264 \354\260\250\n"
"\354\260\276 \352\270\260", 0));
        PARKscene_2->setText(QApplication::translate("home_ui", "PARK2", 0));
        PARKscene_4->setText(QApplication::translate("home_ui", "\353\217\214 \354\225\204\n"
"\352\260\200 \352\270\260", 0));
        PARK_INFO_SCENE_2->setText(QApplication::translate("home_ui", "\n"
"PARK1", 0));
        PARK1_camera->setText(QString());
        PARK1_BACKGROUND->setText(QString());
        PARK1_5->setText(QString());
        PARK1_6->setText(QString());
        PARK1_4->setText(QString());
        PARK1_1->setText(QString());
        PARK1_2->setText(QString());
        PARK1_3->setText(QString());
        PARK1_go_PARK2->setText(QApplication::translate("home_ui", "PARK2", 0));
        PARK1_go_HOME->setText(QApplication::translate("home_ui", "\355\231\210\354\234\274\353\241\234", 0));
        PARK1_camera_txt->setText(QApplication::translate("home_ui", "\354\271\264\353\251\224\353\235\274\353\263\264\352\270\260", 0));
        PARK1_go_Park_select->setText(QApplication::translate("home_ui", "\354\243\274\354\260\250\354\236\245 \354\204\240\355\203\235\354\234\274\353\241\234", 0));
    } // retranslateUi

};

namespace Ui {
    class home_ui: public Ui_home_ui {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_HOME_UI_H
